### ISSUE TITLE
Mockup pagina

### ISSUE THREAD

**Issue by AndresSantosSanabria** [Ciclo4-ucaldas/G49-Desarrolladores-del-futuro#21]
Crear el mockup de cada actor y la pagina principal

- [ ] tener una pagina principal
- [ ] tener los primeros formularios

**Comment by sanroq** [comment]
Se realiza moockup de la vista previa de la pagina.

![Moockuptienda](https://user-images.githubusercontent.com/85202236/200863919-9d8c6a73-0620-4c76-b5eb-634645dbd900.png)

**Comment by JquincheBD** [comment]
Se aprueba sprint, todo excelente
